### PR TITLE
Fix compile error on Apple M1 processors

### PR DESCRIPTION
**Pull request by bsergean**
See #118

### CODE REVIEW

**Comment by BrianNichols** [comment]
We hope to merge this change in the next C client release, but this is just the first step towards ARM support. The C client may require additional memory fences on ARM based cpus that are not necessary on Intel cpus.

**Comment by bsergean** [comment]
Thanks / apparently there are also some problems with the submodules so this small PR might be just the tip of the iceberg. Looking forward this arm support.

**Comment by BrianNichols** [comment]
C client 5.2.8 is released with the makefile change: https://download.aerospike.com/download/client/c/notes.html#5.2.8

**Comment by bsergean** [comment]
Thank you !

We managed to get the client to work on M1 in our fork, I think the other required change was to update another submodule (one that had not been updated for a year or so).

**Pull request closed without merging**
