### PR TITLE
Add support for FreeBSD

### PR DESCRIPTION
**Pull request by Martinfx**
Hello, this is pull request for support FreeBSD 
Thank you M.

### CODE REVIEW

**Comment by BrianNichols** [comment]
The port to FreeBSD will require more changes than what is in this pull request.  We are looking into it further.

**Comment by Martinfx** [comment]
Yes, the problem are submodules this is only commit for aerospike-client-c . Can i send commits for submodule here ?

**Comment by BrianNichols** [comment]
We have completed the port to FreeBSD on the client and submodules.  They will appear in the next C client release.

Note that FreeBSD is not officially supported.  The unit tests pass, but no other testing resources have been assigned to this platform.

**Comment by Martinfx** [comment]
@BrianNichols this is good news, i will be wait for next release.
M.

**Comment by BrianNichols** [comment]
C client 4.3.13 released.

https://www.aerospike.com/download/client/c/4.3.13/

**Pull request closed without merging**
